version: "3.7"
services:
        flask:
                build: 
                        context: .
                        dockerfile: Dockerfileflask
                container_name: flask_restful_app
                restart: always
                expose:
                        - 5000
        nginx:
                build:
                        context: .
                        dockerfile: Dockerfilenginx
                container_name: nginx-flask
                restart: always
                ports:
                        - "80:80"
